login_button = "//span[text()='ورود | ثبت نام']"
username_textbox = "Username"
next_step = "//a[contains(@class,'btn btn-primary')]"
password_textbox = "Password"
submit = "//a[contains(@class,'btn btn-primary')]"
user_profile = "//img[@src='/assets/images/header/profile-dropdown-arrow.svg']"
mainpage_button_xpath = "//div[text()='اتومیتد تست']"
job_group_filter = "//div[text()='گروه شغلی']"
filter_selection = "(//span[@class='ng-option-label ng-star-inserted'])[3]"
search_in_jobs = "//button[text()='جستجو در مشاغل ']"
post_job_selection = "//div[contains(@class,'mr-3 d-flex')]"
apply_for_job = "//button[text()='ارسال رزومه']"
check_apply_for_job = "//h1[text()=' رزومه شما با موفقیت برای کارفرما ارسال شد. ']"
check_apply_for_suggested_jobs = "//h2[text()='رزومه شما با موفقیت ارسال شد']"
close_check_apply_modal = "//img[@alt='بستن']"
logout = "//p[text()='خروج از حساب']"
jobs_page = "//a[@href='/jobs']"
search_job = "//input[@placeholder='عنوان شغلی یا شرکت …']"
search_job_in_job_group_filter = "//input[@placeholder='جستجو...']"
select_job_in_job_group_filter = "//span[text()='توسعه نرم افزار و برنامه نویسی']"
number_of_jobs = "//span[@class='ng-star-inserted']"
search_in_jobs_page = "//button[text()=' جستجو در مشاغل ']"
confirm_job_page = "//p[text()=' متوجه شدم ']"
recommended_jobs_page = "//a[@href='/recommended-jobs']"
check_apply_for_recommended_jobs_page = "//div[text()='رزومه شما با موفقیت ارسال شد']"
