login_button = "//span[text()='ورود | ثبت نام']"
username_textbox = "Username"
next_step = "//a[contains(@class,'btn btn-primary')]"
password_textbox = "Password"
submit = "//a[contains(@class,'btn btn-primary')]"
search_job = "//input[contains(@class,'keyword-input mr-2')]"
search_btn = "//button[text()='جستجو در مشاغل ']"
group_job_filter = "//div[text()='گروه شغلی']"
group_job_option = "//span[text()='توسعه نرم افزار و برنامه نویسی']"
sanat_filter = "//p[text()='صنعت']"
sanat_option = "//label[text()='فناوری اطلاعات / نرم افزار و سخت افزار']"
show_result = "//button[text()='مشاهده نتایج']"
city_filter = "//input[@placeholder='شهر']"
city_option = "//label[text()='تهران']"
option_tree = "//span[text()='تهران']"
level_filter = "//p[text()='سطح ارشدیت']"
level_option = "//label[text()='کارشناس']"
send_resume = "//button[text()='ارسال رزومه']"
close_check_apply_modal = "//img[@alt='بستن']"
new_jobs = "select"
